"""Initial migration

Revision ID: fb02ab975452
Revises: 
Create Date: 2017-07-28 10:46:26.048588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb02ab975452'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_address',
    sa.Column('email', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('email',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('sender', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('preffered_body', sa.Text(), nullable=True),
    sa.Column('plaintext_body', sa.Text(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('rtf_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sender'], ['email_address.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ccs',
    sa.Column('email_id', sa.Text(), nullable=True),
    sa.Column('email_address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_address'], ['email_address.email'], ),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], )
    )
    op.create_table('email_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Text(), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('mimetype', sa.Text(), nullable=True),
    sa.Column('file', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.Text(), nullable=True),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('key', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter', sa.Text(), nullable=True),
    sa.Column('report_time', sa.DateTime(), nullable=True),
    sa.Column('email_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tos',
    sa.Column('email_id', sa.Text(), nullable=True),
    sa.Column('email_address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['email_address'], ['email_address.email'], ),
    sa.ForeignKeyConstraint(['email_id'], ['email.id'], )
    )
    op.create_table('file_hash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('hash_type', sa.Text(), nullable=True),
    sa.Column('hash_value', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['email_attachment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_hash')
    op.drop_table('tos')
    op.drop_table('report')
    op.drop_table('email_header')
    op.drop_table('email_attachment')
    op.drop_table('ccs')
    op.drop_table('email')
    op.drop_table('email_address')
    # ### end Alembic commands ###
